name: Unit Test - Reusable Workflow

on:
    workflow_call:


jobs:
    unit-testing:
        name: Unit Testing
        container:
          image: node:20

        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
    
        - name: Cache NPM dependencies
          uses: actions/cache@v4
          with:
            key: "${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}"
            path: node_modules

        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          run: npm test
          
        - name: Archive Test Result
          uses: actions/upload-artifact@v4
          if: always()
          with:
            name: Mocha-Test-Result
            path: test-results.xml