name: Unit Test - Reusable Workflow

on:
    workflow_call:
      inputs:
        MONGO_URI:
          required: true
          type: string
        MONGO_USERNAME:
          required: true
          type: string
      secrets:
        MONGO_PASSWORD:
          required: true

      
jobs:
    unit-testing:
        name: Unit Testing
        container:
          image: node:20

        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
    
        - name: Npm Caching and Install - My Custom Action
          uses: Devops-jonathan/my-first-custom-action@1.0.0
    
        - name: Unit Testing
          run: npm test
          env:
            MONGO_URI: ${{ inputs.MONGO_URI }}
            MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
            MONGO_USERNAME: ${{ inputs.MONGO_USERNAME}}
          
        - name: Archive Test Result
          uses: actions/upload-artifact@v4
          if: always()
          with:
            name: Mocha-Test-Result
            path: test-results.xml